version: '3'

services:
  shop:
    container_name: shop
    image: dockware/dev:latest
    ports:
      - "22:22"     # ssh
      - "80:80"     # apache2
      - "443:443"   # apache2 https
      - "8888:8888" # watch admin
      - "9998:9998" # watch storefront proxy
      - "9999:9999" # watch storefront
      - "3306:3306" # mysql port
    volumes:
       - "./shopware/custom/plugins/AsamFieldPlugin:/var/www/html/custom/plugins/AsamFieldPlugin"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
      - XDEBUG_REMOTE_HOST=172.17.0.1

## ***********************************************************************
##  NETWORKS
## ***********************************************************************
networks:
  web:
    external: false
